[workspace]
members = [
    "kernel",
    "common",
    # "userland"  # 暂时禁用：userland 还未配置为 no_std 环境
]
resolver = "2"

# 针对所有 crate 的优化配置
[profile.release]
lto = true        # 链接时优化 (极快)
opt-level = 3
panic = "abort"   # 减小体积

[profile.dev]
panic = "abort"